# Nyarch custom settings
# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# used to make btrfs work.
#
---

i18n:
    name: "detecting btrfs file system"

dontChroot: false
timeout: 999
script:
    - /etc/calamares/modules/btrfs.sh
